ROOT: "."
sub2root: "../../"
src: "src/"
log: "logs/"
out: "out/"
src_data: "src/data/"
src_data_mgt: "src/data-management/"
src_analysis: "src/analysis/"
src_lib: "src/lib/"
src_tables: "src/tables/"
src_graphs: "src/graphs/"
src_paper: "src/paper/"

out_analysis: "out/analysis/"
out_data: "out/data/"
out_graphs: "out/graphs/"
out_tables: "out/tables/"
out_paper: "out/paper/"
